version: '3.6'

services:
  app: 
    build: 
      context: .
      target: debug
    volumes:
      - ./dist/src:/usr/src/app/dist/src/ # same folder structure on local machine and docker container
    ports:
      - "8080:8080" 
      - "9229:9229"
    command: npm run debug